apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheusdatasource
    
  # - name: Google Cloud Monitoring
  #   type: stackdriver
  #   access: proxy
  #   isDefault: false
  #   editable: true
  #   jsonData:
  #     defaultProject: eu0:observability-epam
  #     authenticationType: "gce"
  #   uid: stackdriverdatasource

  - name: Alertmanager
    type: alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    uid: alertmanagerdatasource